#!/usr/bin/python3
from sys import argv

infile = "a.asm"
outfile = "a.e23"
if len(argv) > 1:
    infile = argv[1]
if len(argv) > 2:
    outfile = argv[2]
lines = map(lambda l: l.strip(), open(infile, "r").readlines())


class Assembler:
    vars: dict[str, int] = {}
    labels: dict[str, int] = {}

    current_address: int = 0
    lines: list[str]

    def __init__(self, lines: list[str]):
        self.lines = lines

    def pass1(self) -> None:
        for line in self.lines:
            pass
